site_name: RPC Dart
site_description: Official documentation for the RPC Dart library
site_url: https://nogipx.github.io/rpc_dart/
repo_url: https://github.com/nogipx/rpc_dart
repo_name: nogipx/rpc_dart
edit_uri: ''

nav:
  - Home: index.md
  - Getting Started: getting-started.md

  - Core:
      - Framework: core/rpc_dart.md
      - Code Generation: core/generator.md
      - Compression: core/compression.md
      - OpenTelemetry: core/opentelemetry.md

  - Transports:
      - Choosing a Transport: transports/index.md
      - InMemory: transports/inmemory.md
      - HTTP/2: transports/http2.md
      - HTTP/1.1: transports/http.md
      - WebSocket: transports/websocket.md
      - Isolate: transports/isolate.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - macros:
      module_name: macros
