name: rpc_dart
description: gRPC-inspired library built on pure Dart
version: 1.7.0
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://github.com/nogipx/rpc_dart
issue_tracker: https://github.com/nogipx/rpc_dart/issues
funding:
  - https://liberapay.com/nogipx

topics:
  - rpc
  - grpc
  - cord
  - contract-oriented-remote-domains
  - streams

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dev_dependencies:
  lints: 3.0.0
  test: 1.25.5

