# SPDX-FileCopyrightText: 2025 Karim "nogipx" Mamatkazin <nogipx@gmail.com>
# SPDX-FileCopyrightText: 2026 Karim "nogipx" Mamatkazin <nogipx@gmail.com>
#
# SPDX-License-Identifier: MIT

name: rpc_dart_generator_consumer
description: Example consumer of rpc_dart and rpc_dart_generator
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  rpc_dart: ^2.6.3
  json_annotation: ^4.10.0
  rpc_dart_grpc_reflection:
    path: ../../rpc_dart_grpc_reflection

  rpc_dart_http2: any
dependency_overrides:
  rpc_dart:
    path: ../../rpc_dart
  rpc_dart_grpc_reflection:
    path: ../../rpc_dart_grpc_reflection

dev_dependencies:
  build_runner: ^2.11.1
  json_serializable: ^6.12.0