name: rpc_dart
description: Transport-agnostic RPC framework with contracts, streaming and included transports.
version: 2.2.2
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://rpc.nogipx.dev
issue_tracker: https://github.com/nogipx/rpc_dart/issues

topics:
  - rpc

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: 3.0.0
  test: 1.25.5
