name: rpc_dart
description: >-
  Платформонезависимая реализация RPC (Remote Procedure Call)
  протокола для Dart и Flutter.
version: 0.3.0
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://github.com/nogipx/rpc_dart
issue_tracker: https://github.com/nogipx/rpc_dart/issues

topics:
  - rpc
  - streaming
  - grpc
  - bidirectional
  - communication

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

funding:
  - https://liberapay.com/nogipx

example: example/README.md