name: rpc_dart_data
description: Data service layer (CRUD + querying + change streams) built on rpc_dart.
version: 3.1.0
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://rpc.nogipx.dev
issue_tracker: https://github.com/nogipx/rpc_dart/issues

environment:
  sdk: '>=3.10.0 <4.0.0'

hooks:
  user_defines:
    sqlite3:
      source: sqlite3mc

dependencies:
  rpc_dart: ^2.3.4
  licensify: ^4.4.0
  equatable: ^2.0.7
  collection: ^1.19.1
  meta: ^1.17.0
  path: ^1.9.1
  sqlite3: ^3.1.1
  async: ^2.13.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  build_runner: ^2.9.0
