name: rpc_dart_websocket
description: Web-safe subset of rpc_dart_transports providing WebSocket caller/responder transports (caller + server) for Dart2JS/WASM builds.
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.10.1

topics:
  - rpc
  - websocket

dependency_overrides:
  rpc_dart:
    ^3.0.1 ../../core/rpc_dart

dependencies:
  rpc_dart: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
