# SPDX-FileCopyrightText: 2026 Karim "nogipx" Mamatkazin <nogipx@gmail.com>
#
# SPDX-License-Identifier: MIT

name: rpc_dart_compression
description: Cross-platform compression codecs for rpc_dart (web/JS/Wasm compatible).
version: 0.2.0
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://rpc.nogipx.dev
issue_tracker: https://github.com/nogipx/rpc_dart/issues

environment:
  sdk: ^3.10.1

resolution: workspace

topics:
  - rpc
  - compression

dependencies:
  rpc_dart: '>=5.0.0 <6.0.0'
  archive: ^4.0.9

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
