targets:
  $default:
    builders:
      rpc_dart_generator|rpc_dart:
        enabled: true

builders:
  rpc_dart:
    import: "package:rpc_dart_generator/builder.dart"
    builder_factories: ["rpcDartBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
