name: rpc_dart_generator
description: Code generator for rpc_dart callers and responders.
version: 0.1.4
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://rpc.nogipx.dev
issue_tracker: https://github.com/nogipx/rpc_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^10.0.2
  build: ^4.0.4
  dart_style: ^3.1.5
  pub_semver: ^2.2.0
  rpc_dart: ^2.4.1
  source_gen: ^4.2.0

dev_dependencies:
  build_runner: ^2.11.1
  build_test: ^3.5.7
  lints: ^6.1.0
  package_config: ^2.2.0
  path: ^1.9.1
  test: ^1.29.0
