# SPDX-FileCopyrightText: 2026 Karim "nogipx" Mamatkazin <nogipx@gmail.com>
#
# SPDX-License-Identifier: MIT

name: rpc_dart_opentelemetry
description: OpenTelemetry tracing, metrics, and logging integration for rpc_dart.
version: 0.3.6
publish_to: none
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://rpc.nogipx.dev
issue_tracker: https://github.com/nogipx/rpc_dart/issues

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  rpc_dart: ^3.3.0
  opentelemetry: ^0.18.0
  fixnum: ^1.1.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
