// SPDX-FileCopyrightText: 2026 Karim "nogipx" Mamatkazin <nogipx@gmail.com>
// SPDX-License-Identifier: MIT

import 'package:rpc_dart/rpc_dart.dart';

import 'descriptor_builder.dart';
import 'proto_parser.dart';
import 'reflection_contract.dart';

/// Registry of gRPC service descriptors for Server Reflection.
///
/// **Protobuf services** — use bytes from generated `.pbjson.dart`:
/// ```dart
/// registry.addFromPbjson(
///   name: 'echo.proto',
///   package: 'echo.v1',
///   messages: [echoRequestDescriptor, echoResponseDescriptor],
///   services: [echoServiceDescriptor],
/// );
/// ```
///
/// **With imports** — register dependencies first, then the importing file:
/// ```dart
/// registry.addFromPbjson(name: 'common.proto', package: 'common.v1', ...);
/// registry.addFromPbjson(
///   name: 'echo.proto',
///   package: 'echo.v1',
///   dependencies: ['common.proto'],
///   ...
/// );
/// ```
///
/// **Codegen native services** — use generated descriptor:
/// ```dart
/// registry.addFileDescriptor(MyServiceNames.grpcDescriptor);
/// ```
class RpcReflectionRegistry {
  // filename → raw FileDescriptorProto bytes
  final Map<String, Uint8List> _files = {};

  // filename → list of dependency filenames (from proto `import` statements)
  final Map<String, List<String>> _dependencies = {};

  // fully-qualified symbol → filename
  final Map<String, String> _symbolToFile = {};

  // all service names (fully qualified), in registration order
  final List<String> _serviceNames = [];

  // Logger used to surface missing-dependency warnings. Injected by the user
  // or lazily built on first warning (see [_log]).
  LogScope? _logger;

  /// Creates a registry.
  ///
  /// [logger] — optional [LogScope] used to surface warnings when a reflection
  /// response would omit an unregistered (declared or transitive) dependency.
  /// Pass an endpoint's scope to route warnings through the application's
  /// [LogController]. When omitted, warnings are emitted to the console via a
  /// lazily-created default [LogController] backed by a [ConsoleOutput].
  RpcReflectionRegistry({LogScope? logger}) : _logger = logger;

  /// Registers a single `FileDescriptorProto`.
  ///
  /// Pass bytes generated by rpc_dart_generator (e.g. `MyServiceNames.grpcDescriptor`).
  void addFileDescriptor(Uint8List fileDescriptorProtoBytes) {
    _registerParsed(parseFileDescriptorProto(fileDescriptorProtoBytes));
  }

  /// Registers a protobuf service using descriptor bytes from generated `.pbjson.dart`.
  ///
  /// [name] — proto filename (e.g. `'echo.proto'`)
  /// [package] — proto package (e.g. `'echo.v1'`), empty string if none
  /// [dependencies] — list of imported proto filenames (e.g. `['common.proto']`)
  /// [messages] — list of message descriptor bytes (e.g. `echoRequestDescriptor`)
  /// [services] — list of service descriptor bytes (e.g. `echoServiceDescriptor`)
  ///
  /// Example:
  /// ```dart
  /// registry.addFromPbjson(
  ///   name: 'echo.proto',
  ///   package: 'echo.v1',
  ///   messages: [echoRequestDescriptor, echoResponseDescriptor],
  ///   services: [echoServiceDescriptor],
  /// );
  /// ```
  void addFromPbjson({
    required String name,
    required String package,
    required List<Uint8List> messages,
    required List<Uint8List> services,
    List<String> dependencies = const [],
  }) {
    var builder = RpcFileDescriptorBuilder(name: name, package: package);
    for (final dep in dependencies) {
      builder = builder.addDependency(dep);
    }
    for (final m in messages) {
      builder = builder.addMessageBytes(m);
    }
    for (final s in services) {
      builder = builder.addServiceBytes(s);
    }
    addFileDescriptor(builder.build());
  }

  /// All registered service names (fully qualified).
  List<String> get serviceNames => List.unmodifiable(_serviceNames);

  /// Whether any files with full schema have been registered.
  bool get hasDescriptors => _files.isNotEmpty;

  /// Returns FileDescriptorProto bytes for [filename] plus all registered
  /// transitive dependencies, or null if [filename] is not registered.
  ///
  /// Dependencies that are declared (via proto `import`) but not registered
  /// (e.g. well-known types) are skipped, producing a partial descriptor set.
  /// When this happens a WARNING is emitted naming the missing files; the
  /// partial set is still returned so existing clients keep working.
  List<Uint8List>? fileByFilename(String filename) {
    if (!_files.containsKey(filename)) return null;
    return _resolveWithDeps(filename);
  }

  /// Returns FileDescriptorProto bytes for the file containing [symbol] plus
  /// all registered transitive dependencies, or null if not found.
  ///
  /// [symbol] may be a service name, message type name, nested type, or enum.
  /// Accepts both `foo.v1.Bar` and `.foo.v1.Bar` forms.
  ///
  /// Like [fileByFilename], declared-but-unregistered dependencies are skipped
  /// and a WARNING naming them is emitted; the partial set is still returned.
  List<Uint8List>? fileContainingSymbol(String symbol) {
    final filename =
        _symbolToFile[symbol] ??
        _symbolToFile[symbol.startsWith('.')
            ? symbol.substring(1)
            : '.$symbol'];
    return filename != null ? _resolveWithDeps(filename) : null;
  }

  /// Returns the set of declared dependency filenames that are reachable from
  /// any registered file but are themselves not registered.
  ///
  /// An empty result means the transitive closure of every registered file is
  /// complete and reflection responses will never be silently truncated. A
  /// non-empty result lists the proto files a reflection client would be unable
  /// to resolve (e.g. unregistered well-known types). Useful as a startup
  /// assertion:
  /// ```dart
  /// final missing = registry.missingDependencies();
  /// if (missing.isNotEmpty) {
  ///   throw StateError('Reflection registry incomplete: $missing');
  /// }
  /// ```
  Set<String> missingDependencies() {
    final missing = <String>{};
    for (final entry in _dependencies.entries) {
      for (final dep in entry.value) {
        if (!_files.containsKey(dep)) missing.add(dep);
      }
    }
    return missing;
  }

  /// Registers reflection contracts (v1 + v1alpha) on [endpoint].
  ///
  /// Call after registering all service contracts:
  /// ```dart
  /// endpoint.registerServiceContract(MyServiceResponder());
  /// registry.attachTo(endpoint);
  /// ```
  void attachTo(RpcResponderEndpoint endpoint) {
    for (final contract in ServerReflectionContract.both(this)) {
      endpoint.registerServiceContract(contract);
    }
  }

  List<Uint8List> _resolveWithDeps(String filename) {
    final result = <Uint8List>[];
    final visited = <String>{};
    final missing = <String>{};
    _collectDeps(filename, result, visited, missing);
    if (missing.isNotEmpty) {
      _warnMissing(filename, missing);
    }
    return result;
  }

  void _collectDeps(
    String filename,
    List<Uint8List> result,
    Set<String> visited,
    Set<String> missing,
  ) {
    if (!visited.add(filename)) return;
    final bytes = _files[filename];
    if (bytes == null) {
      // Declared dependency that was never registered (e.g. an unregistered
      // well-known type). Record it so the caller can be warned, then skip:
      // the partial set is still returned to stay non-breaking.
      missing.add(filename);
      return;
    }
    result.add(bytes);
    for (final dep in (_dependencies[filename] ?? const [])) {
      _collectDeps(dep, result, visited, missing);
    }
  }

  void _warnMissing(String requested, Set<String> missing) {
    final sorted = missing.toList()..sort();
    _log().warning(
      'Reflection response for "$requested" is INCOMPLETE: '
      '${sorted.length} declared dependency file(s) are not registered and '
      'were omitted: ${sorted.join(', ')}. '
      'Register them (e.g. via addFileDescriptor/addFromPbjson) so reflection '
      'clients can resolve the full descriptor set.',
      data: {'requestedFile': requested, 'missingFiles': sorted},
    );
  }

  /// Returns the logger, lazily building a console-backed default the first
  /// time a warning needs to be surfaced and none was injected.
  LogScope _log() {
    return _logger ??= LogController(
      outputs: [ConsoleOutput()],
    ).scope('rpc_dart_grpc_reflection');
  }

  void _registerParsed(ParsedFileDescriptor proto) {
    _files[proto.name] = proto.rawBytes;
    _dependencies[proto.name] = proto.dependencies;

    final prefix = proto.package.isEmpty ? '' : '${proto.package}.';

    for (final svc in proto.services) {
      final fqn = '$prefix$svc';
      _symbolToFile[fqn] = proto.name;
      if (!_serviceNames.contains(fqn)) {
        _serviceNames.add(fqn);
      }

      // Methods too. The reflection proto documents file_containing_symbol as
      // taking `<package>.<service>[.<method>]`, and `grpcurl describe
      // pkg.Service.Method` relies on it. Only services, messages and enums
      // were indexed, so a real gRPC client got "Symbol not found" for every
      // method while the enclosing service resolved fine -- verified against
      // grpcurl 1.9.3, where `describe echo.v1.EchoService` and
      // `describe echo.v1.EchoRequest` both worked and
      // `describe echo.v1.EchoService.Echo` did not.
      for (final method in proto.serviceMethods[svc] ?? const <String>[]) {
        _symbolToFile['$fqn.$method'] = proto.name;
      }
    }

    for (final msg in proto.messageTypes) {
      final fqn = '.$prefix$msg';
      _symbolToFile[fqn] = proto.name;
      _symbolToFile['$prefix$msg'] = proto.name;
    }

    for (final enm in proto.enumTypes) {
      final fqn = '.$prefix$enm';
      _symbolToFile[fqn] = proto.name;
      _symbolToFile['$prefix$enm'] = proto.name;
    }
  }
}
