// SPDX-FileCopyrightText: 2026 Karim "nogipx" Mamatkazin <nogipx@gmail.com>
// SPDX-License-Identifier: MIT

import 'package:rpc_dart/rpc_dart.dart';

import 'descriptor_builder.dart';
import 'proto_parser.dart';
import 'reflection_contract.dart';

/// Registry of gRPC service descriptors for Server Reflection.
///
/// **Protobuf services** — use bytes from generated `.pbjson.dart`:
/// ```dart
/// registry.addFromPbjson(
///   name: 'echo.proto',
///   package: 'echo.v1',
///   messages: [echoRequestDescriptor, echoResponseDescriptor],
///   services: [echoServiceDescriptor],
/// );
/// ```
///
/// **With imports** — register dependencies first, then the importing file:
/// ```dart
/// registry.addFromPbjson(name: 'common.proto', package: 'common.v1', ...);
/// registry.addFromPbjson(
///   name: 'echo.proto',
///   package: 'echo.v1',
///   dependencies: ['common.proto'],
///   ...
/// );
/// ```
///
/// **Codegen native services** — use generated descriptor:
/// ```dart
/// registry.addFileDescriptor(MyServiceNames.grpcDescriptor);
/// ```
class RpcReflectionRegistry {
  // filename → raw FileDescriptorProto bytes
  final Map<String, Uint8List> _files = {};

  // filename → list of dependency filenames (from proto `import` statements)
  final Map<String, List<String>> _dependencies = {};

  // fully-qualified symbol → filename
  final Map<String, String> _symbolToFile = {};

  // all service names (fully qualified), in registration order
  final List<String> _serviceNames = [];

  /// Registers a single `FileDescriptorProto`.
  ///
  /// Pass bytes generated by rpc_dart_generator (e.g. `MyServiceNames.grpcDescriptor`).
  void addFileDescriptor(Uint8List fileDescriptorProtoBytes) {
    _registerParsed(parseFileDescriptorProto(fileDescriptorProtoBytes));
  }

  /// Registers a protobuf service using descriptor bytes from generated `.pbjson.dart`.
  ///
  /// [name] — proto filename (e.g. `'echo.proto'`)
  /// [package] — proto package (e.g. `'echo.v1'`), empty string if none
  /// [dependencies] — list of imported proto filenames (e.g. `['common.proto']`)
  /// [messages] — list of message descriptor bytes (e.g. `echoRequestDescriptor`)
  /// [services] — list of service descriptor bytes (e.g. `echoServiceDescriptor`)
  ///
  /// Example:
  /// ```dart
  /// registry.addFromPbjson(
  ///   name: 'echo.proto',
  ///   package: 'echo.v1',
  ///   messages: [echoRequestDescriptor, echoResponseDescriptor],
  ///   services: [echoServiceDescriptor],
  /// );
  /// ```
  void addFromPbjson({
    required String name,
    required String package,
    required List<Uint8List> messages,
    required List<Uint8List> services,
    List<String> dependencies = const [],
  }) {
    var builder = RpcFileDescriptorBuilder(name: name, package: package);
    for (final dep in dependencies) {
      builder = builder.addDependency(dep);
    }
    for (final m in messages) {
      builder = builder.addMessageBytes(m);
    }
    for (final s in services) {
      builder = builder.addServiceBytes(s);
    }
    addFileDescriptor(builder.build());
  }

  /// All registered service names (fully qualified).
  List<String> get serviceNames => List.unmodifiable(_serviceNames);

  /// Whether any files with full schema have been registered.
  bool get hasDescriptors => _files.isNotEmpty;

  /// Returns FileDescriptorProto bytes for [filename] plus all registered
  /// transitive dependencies, or null if [filename] is not registered.
  ///
  /// Dependencies that are not registered (e.g. well-known types) are skipped.
  List<Uint8List>? fileByFilename(String filename) {
    if (!_files.containsKey(filename)) return null;
    return _resolveWithDeps(filename);
  }

  /// Returns FileDescriptorProto bytes for the file containing [symbol] plus
  /// all registered transitive dependencies, or null if not found.
  ///
  /// [symbol] may be a service name, message type name, nested type, or enum.
  /// Accepts both `foo.v1.Bar` and `.foo.v1.Bar` forms.
  List<Uint8List>? fileContainingSymbol(String symbol) {
    final filename =
        _symbolToFile[symbol] ??
        _symbolToFile[symbol.startsWith('.') ? symbol.substring(1) : '.$symbol'];
    return filename != null ? _resolveWithDeps(filename) : null;
  }

  /// Registers reflection contracts (v1 + v1alpha) on [endpoint].
  ///
  /// Call after registering all service contracts:
  /// ```dart
  /// endpoint.registerServiceContract(MyServiceResponder());
  /// registry.attachTo(endpoint);
  /// ```
  void attachTo(RpcResponderEndpoint endpoint) {
    for (final contract in ServerReflectionContract.both(this)) {
      endpoint.registerServiceContract(contract);
    }
  }

  List<Uint8List> _resolveWithDeps(String filename) {
    final result = <Uint8List>[];
    final visited = <String>{};
    _collectDeps(filename, result, visited);
    return result;
  }

  void _collectDeps(String filename, List<Uint8List> result, Set<String> visited) {
    if (!visited.add(filename)) return;
    final bytes = _files[filename];
    if (bytes == null) return; // not registered — skip (e.g. well-known types)
    result.add(bytes);
    for (final dep in (_dependencies[filename] ?? const [])) {
      _collectDeps(dep, result, visited);
    }
  }

  void _registerParsed(ParsedFileDescriptor proto) {
    _files[proto.name] = proto.rawBytes;
    _dependencies[proto.name] = proto.dependencies;

    final prefix = proto.package.isEmpty ? '' : '${proto.package}.';

    for (final svc in proto.services) {
      final fqn = '$prefix$svc';
      _symbolToFile[fqn] = proto.name;
      if (!_serviceNames.contains(fqn)) {
        _serviceNames.add(fqn);
      }
    }

    for (final msg in proto.messageTypes) {
      final fqn = '.$prefix$msg';
      _symbolToFile[fqn] = proto.name;
      _symbolToFile['$prefix$msg'] = proto.name;
    }

    for (final enm in proto.enumTypes) {
      final fqn = '.$prefix$enm';
      _symbolToFile[fqn] = proto.name;
      _symbolToFile['$prefix$enm'] = proto.name;
    }
  }
}
