// SPDX-FileCopyrightText: 2026 Karim "nogipx" Mamatkazin <nogipx@gmail.com>
// SPDX-License-Identifier: MIT

import 'package:rpc_dart/rpc_dart.dart';

import 'descriptor_builder.dart';
import 'proto_parser.dart';
import 'reflection_contract.dart';

/// Registry of gRPC service descriptors for Server Reflection.
///
/// **Protobuf services** — use bytes from generated `.pbjson.dart`:
/// ```dart
/// registry.addFromPbjson(
///   name: 'echo.proto',
///   package: 'echo.v1',
///   messages: [echoRequestDescriptor, echoResponseDescriptor],
///   services: [echoServiceDescriptor],
/// );
/// ```
///
/// **Codegen native services** — use generated descriptor:
/// ```dart
/// registry.addFileDescriptor(MyServiceNames.grpcDescriptor);
/// ```
class RpcReflectionRegistry {
  // filename → raw FileDescriptorProto bytes
  final Map<String, Uint8List> _files = {};

  // fully-qualified symbol → filename
  final Map<String, String> _symbolToFile = {};

  // all service names (fully qualified), in registration order
  final List<String> _serviceNames = [];

  /// Registers a single `FileDescriptorProto`.
  ///
  /// Pass bytes generated by rpc_dart_generator (e.g. `MyServiceNames.grpcDescriptor`).
  void addFileDescriptor(Uint8List fileDescriptorProtoBytes) {
    _registerParsed(parseFileDescriptorProto(fileDescriptorProtoBytes));
  }

  /// Registers a protobuf service using descriptor bytes from generated `.pbjson.dart`.
  ///
  /// [name] — proto filename (e.g. `'echo.proto'`)
  /// [package] — proto package (e.g. `'echo.v1'`), empty string if none
  /// [messages] — list of message descriptor bytes (e.g. `echoRequestDescriptor`)
  /// [services] — list of service descriptor bytes (e.g. `echoServiceDescriptor`)
  ///
  /// Example:
  /// ```dart
  /// registry.addFromPbjson(
  ///   name: 'echo.proto',
  ///   package: 'echo.v1',
  ///   messages: [echoRequestDescriptor, echoResponseDescriptor],
  ///   services: [echoServiceDescriptor],
  /// );
  /// ```
  void addFromPbjson({
    required String name,
    required String package,
    required List<Uint8List> messages,
    required List<Uint8List> services,
  }) {
    var builder = RpcFileDescriptorBuilder(name: name, package: package);
    for (final m in messages) {
      builder = builder.addMessageBytes(m);
    }
    for (final s in services) {
      builder = builder.addServiceBytes(s);
    }
    addFileDescriptor(builder.build());
  }

  /// All registered service names (fully qualified).
  List<String> get serviceNames => List.unmodifiable(_serviceNames);

  /// Returns raw FileDescriptorProto bytes for [filename], or null if not found.
  Uint8List? fileByFilename(String filename) => _files[filename];

  /// Returns raw FileDescriptorProto bytes for the file containing [symbol].
  ///
  /// [symbol] may be a service name, message type name, etc.
  Uint8List? fileContainingSymbol(String symbol) {
    final filename =
        _symbolToFile[symbol] ??
        _symbolToFile[symbol.startsWith('.')
            ? symbol.substring(1)
            : '.$symbol'];
    return filename != null ? _files[filename] : null;
  }

  /// Whether any files with full schema have been registered.
  bool get hasDescriptors => _files.isNotEmpty;

  /// Registers reflection contracts (v1 + v1alpha) on [endpoint].
  ///
  /// Call after registering all service contracts:
  /// ```dart
  /// endpoint.registerServiceContract(MyServiceResponder());
  /// registry.attachTo(endpoint);
  /// ```
  void attachTo(RpcResponderEndpoint endpoint) {
    for (final contract in ServerReflectionContract.both(this)) {
      endpoint.registerServiceContract(contract);
    }
  }

  void _registerParsed(ParsedFileDescriptor proto) {
    _files[proto.name] = proto.rawBytes;

    final prefix = proto.package.isEmpty ? '' : '${proto.package}.';

    for (final svc in proto.services) {
      final fqn = '$prefix$svc';
      _symbolToFile[fqn] = proto.name;
      if (!_serviceNames.contains(fqn)) {
        _serviceNames.add(fqn);
      }
    }

    for (final msg in proto.messageTypes) {
      final fqn = '.$prefix$msg';
      _symbolToFile[fqn] = proto.name;
      _symbolToFile['$prefix$msg'] = proto.name;
    }
  }
}
